'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const pw=require(process.env.QA_PLAYWRIGHT||path.join(process.env.QA_NODE_MODULES||path.resolve('node_modules'),'playwright'));
const OUT=path.resolve(process.env.QA_V22_OUTPUT||'qa-v22'),ROOT=path.resolve('solaris-dist'),HOST='http://127.0.0.1:8192';fs.mkdirSync(OUT,{recursive:true});let server;
const snap=p=>p.evaluate(()=>SolarisQuest.snapshot()),aud=(p,measure=false)=>p.evaluate(m=>SolarisSound.snapshot(m),measure);
async function load(p){if(process.env.QA_INLINE)await p.setContent(require(process.env.QA_INLINE)());else await p.goto(HOST+'/jogo/');await p.waitForFunction(()=>window.SolarisQuest?.snapshot().ready);}
async function shot(p,name){await p.screenshot({path:path.join(OUT,name+'.png'),timeout:5000});}
function checkpoint(name){console.log('CHECKPOINT '+name);fs.writeFileSync(path.join(OUT,'checkpoint.txt'),name);}
async function tapControl(p,id){const el=p.locator('#'+id);await el.waitFor({state:'visible'});const r=await el.boundingBox();const point={x:r.x+r.width/2,y:r.y+r.height/2};assert(await p.evaluate(({x,y,id})=>document.elementFromPoint(x,y)?.closest('#'+id)!=null,{...point,id}),'Control must be hit-testable');const action=(await p.evaluate(()=>navigator.maxTouchPoints>0))?p.touchscreen.tap(point.x,point.y):p.mouse.click(point.x,point.y);let timeout;try{await Promise.race([action,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Native audio input did not return')),6000);})]);}finally{clearTimeout(timeout);}}
async function maxRMS(p){let max=0;for(let i=0;i<10;i++){max=Math.max(max,(await aud(p,true)).rms);await p.waitForTimeout(80);}return max;}
async function input(p,id,v){await p.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(v));}
async function dismiss(p){if(await p.locator('#visitToast').isVisible())await p.click('#visitToastClose');}
async function visit(p,id){await dismiss(p);await p.click('#bottomNav [data-view="mapView"]');await p.click('#allLocations');await p.click(`[data-place="${id}"]`);await p.click('#walkToPlace');await p.waitForFunction(id=>SolarisQuest.snapshot().state.visited.includes(id),id,{timeout:30000});await p.waitForFunction(()=>SolarisQuest.snapshot().routeLength===0);}
async function main(){if(!process.env.QA_INLINE){server=http.createServer((req,res)=>{let n=decodeURIComponent(new URL(req.url,HOST).pathname);if(n.endsWith('/'))n+='index.html';const f=path.resolve(ROOT,'.'+n);if(!f.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end();}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.jpg':'image/jpeg','.json':'application/json'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8192,'127.0.0.1',r));}
 const reports=[];
 const specs=process.env.QA_INLINE?[{name:'local-mobile',engine:'chromium',width:390,height:844,touch:true}]:[{name:'iphone-webkit',engine:'webkit',width:390,height:844,touch:true},{name:'desktop-chromium',engine:'chromium',width:1440,height:900,touch:false}];
 for(const spec of specs){const browser=await pw[spec.engine].launch(process.env.QA_INLINE?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{});const c=await browser.newContext({viewport:{width:spec.width,height:spec.height},isMobile:spec.touch,hasTouch:spec.touch,deviceScaleFactor:1,acceptDownloads:true});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{checkpoint('native-dialog '+d.type());await d.accept();});p.setDefaultTimeout(15000);p.setDefaultNavigationTimeout(15000);
 try{await load(p);assert.equal((await aud(p)).state,'uninitialized');assert.equal((await snap(p)).visits,0);await p.fill('#nickname','Franco');await p.click('#startGame');await p.waitForFunction(()=>SolarisQuest.snapshot().visits===1);assert.deepEqual((await snap(p)).state.visited,['portaria']);assert.equal((await snap(p)).coins,15);assert.equal((await snap(p)).xp,20);await shot(p,spec.name+'-journey');await dismiss(p);checkpoint('early-mute');await p.waitForFunction(()=>SolarisSound.snapshot(false).musicTrack?.ready);await tapControl(p,'soundToggle');await p.waitForFunction(()=>SolarisSound.snapshot(false).state==='closed');checkpoint('early-unmute');await tapControl(p,'soundToggle');await p.waitForFunction(()=>SolarisSound.snapshot(false).state==='running');checkpoint('early-resume-ok');
 await p.click('#soundSettings');await input(p,'effectsVolume',0);await input(p,'ambientVolume',0);await input(p,'musicVolume',70);await p.waitForFunction(()=>SolarisSound.snapshot(false).musicTrack?.ready,null,{timeout:15000});await p.waitForTimeout(500);assert(await maxRMS(p)>0.00001,'Music alone generates audible samples');const notes=(await aud(p)).musicTrack.playedNotes;await p.waitForTimeout(1800);assert((await aud(p)).musicTrack.playedNotes>notes,'Continuous authored score advances');await shot(p,spec.name+'-music');await input(p,'musicVolume',0);await p.waitForTimeout(900);assert(await maxRMS(p)<0.000001,'Music mute is independent of master');await input(p,'musicVolume',60);await p.waitForTimeout(500);assert(await maxRMS(p)>0.00001);await p.click('#audioDialog [data-close]');
 // Preview, unlike arrival, never earns rewards or bypasses a phase lock.
 await p.click('#bottomNav [data-view="mapView"]');await p.click('#allLocations');await p.click('[data-place="clube"]');assert.match(await p.locator('#placeAchievement').textContent(),/Primeira visita/);await p.click('#viewPlace');assert.equal((await snap(p)).visits,1);
 for(const id of ['praca','bosque','lago','clube','quadras','hipica','acesso','parque']){const before=await snap(p);await visit(p,id);const after=await snap(p);assert.equal(after.visits,before.visits+1);assert.equal(after.coins-before.coins,after.visits===9?115:15);assert.equal(after.xp-before.xp,after.visits===9?120:20);assert.equal(after.stars,0);console.log(spec.name+' arrival '+id+' verified');}
 assert.equal((await snap(p)).coins,235);assert.equal((await snap(p)).xp,280);await dismiss(p);await p.click('#bottomNav [data-view="passport"]');assert.equal(await p.locator('.visit-stamp.earned').count(),9);await shot(p,spec.name+'-passport');await p.waitForFunction(()=>SolarisSound.snapshot(false).musicTrack.loops>=1,null,{timeout:60000});assert((await aud(p)).musicTrack.loops>=1,'The score loops while exploring');
 const before=await snap(p);await visit(p,'portaria');await visit(p,'portaria');assert.equal((await snap(p)).coins,before.coins);assert.equal((await snap(p)).xp,before.xp);await dismiss(p);
 await p.click('#bottomNav [data-view="rewards"]');await shot(p,spec.name+'-rewards');await p.click('#explorationAwards [data-item="explorador-tree"]');await p.click('#rewardClaim');await p.click('[data-slot="0"]');assert.equal((await snap(p)).state.slots[0],'explorador-tree');await shot(p,spec.name+'-refuge');await p.click('#bottomNav [data-view="journey"]');assert(await p.locator('button[data-level="2"]').isDisabled(),'Exploration does not bypass phase locks');
 await p.click('#bottomNav [data-view="passport"]');const download=p.waitForEvent('download');await p.click('#saveCard');await (await download).saveAs(path.join(OUT,spec.name+'-card.png'));assert(fs.statSync(path.join(OUT,spec.name+'-card.png')).size>10000);const ex=p.waitForEvent('download');await p.click('#exportSave');const save=path.join(OUT,spec.name+'-save.json');await (await ex).saveAs(save);assert.equal(JSON.parse(fs.readFileSync(save)).progress.visited.length,9);
 checkpoint('mute-start');await tapControl(p,'soundToggle');assert.equal((await aud(p)).enabled,false);checkpoint('mute-complete');await p.waitForTimeout(100);assert.equal((await aud(p)).state,'closed');await tapControl(p,'soundToggle');await p.waitForFunction(()=>SolarisSound.snapshot(false).state==='running');checkpoint('unmute-complete');await p.evaluate(()=>dispatchEvent(new Event('pagehide')));await p.waitForFunction(()=>SolarisSound.snapshot(false).state==='closed');checkpoint('pagehide-suspended');assert.equal((await aud(p)).musicTrack.active,false);await tapControl(p,'soundToggle');await p.waitForFunction(()=>SolarisSound.snapshot(false).musicTrack?.active&&SolarisSound.snapshot(false).musicTrack?.ready);checkpoint('pagehide-music-active');await p.waitForTimeout(700);assert(await maxRMS(p)>0.00001);
 if(!process.env.QA_INLINE){checkpoint('reload-start');await p.reload({waitUntil:'domcontentloaded'});checkpoint('reload-document');await p.waitForFunction(()=>SolarisQuest?.snapshot().ready);assert.equal((await aud(p)).state,'uninitialized');checkpoint('resume-start');await p.click('#resumeGame');checkpoint('resume-complete');assert.equal((await snap(p)).coins,235);assert.equal((await snap(p)).state.slots[0],'explorador-tree');await p.click('#bottomNav [data-view="passport"]');const data=JSON.parse(fs.readFileSync(save));data.progress.visited.push('parque','invalid-place','__proto__');checkpoint('import-start');await p.setInputFiles('#importSave',{name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});checkpoint('import-input-complete');await p.waitForTimeout(200);assert.equal((await snap(p)).visits,9);assert.equal((await snap(p)).coins,235);assert.equal((await snap(p)).state.slots[0],'explorador-tree');}
 assert.deepEqual(errors,[]);reports.push({device:spec.name,passed:true,music:true,loopVerified:true,visits:9,oneTimeRewards:true,collection:true,saveImport:true,phaseLocksPreserved:true,errors});
 }catch(e){console.error('ORIGINAL FAILURE',e);fs.writeFileSync(path.join(OUT,'failure.json'),JSON.stringify({device:spec.name,error:e.stack,errors},null,2));try{await shot(p,spec.name+'-FAIL');}catch(se){console.error('Screenshot unavailable:',se.message);}throw e;}finally{await browser.close();}}
 if(!process.env.QA_INLINE){const b=await pw.chromium.launch();const c=await b.newContext();const old={v:2,started:true,name:'Anterior',best:[3,3,3,...Array(12).fill(0)],attempts:Array(15).fill(1),claimed:['folhas'],purchases:['ipe'],slots:['ipe',null,null,null,null,null],outfit:'folhas',transport:'walk',node:0};await c.addInitScript(s=>localStorage.setItem('solaris-conquista-v2',JSON.stringify(s)),old);const p=await c.newPage();await load(p);const s=await snap(p);assert.equal(s.completed,3);assert.equal(s.stars,9);assert.equal(s.coins,220);assert.equal(s.visits,0);assert.equal(s.state.slots[0],'ipe');checkpoint('resume-start');await p.click('#resumeGame');checkpoint('resume-complete');assert.equal((await snap(p)).coins,235);assert.equal((await snap(p)).completed,3);await b.close();reports.push({oldSaveMigration:true,passed:true});}
 fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify({version:'solaris-conquista-v2.2',passed:true,reports},null,2));console.log(JSON.stringify(reports));}
main().then(()=>server?.close()).catch(e=>{console.error(e);server?.close();process.exitCode=1;});
