'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const paths={map:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2V5z M9 3v16 M15 5v16',image:'M4 3h16a1 1 0 011 1v16a1 1 0 01-1 1H4a1 1 0 01-1-1V4a1 1 0 011-1z M3 16l5-5 6 6 3-3 4 4 M15 8h.01',play:'M8 4l12 8-12 8z',pause:'M8 5v14 M16 5v14',help:'M9 9a3 3 0 016 0c0 2-3 2-3 4 M12 17h.01 M22 12a10 10 0 11-20 0 10 10 0 0120 0',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',focus:'M8 3H3v5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M9 9h6v6H9z',expand:'M8 3H3v5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M3 3l6 6 M21 3l-6 6 M21 21l-6-6 M3 21l6-6',collapse:'M9 3v6H3 M15 3v6h6 M15 21v-6h6 M9 21v-6H3',close:'M6 6l12 12 M18 6L6 18',arrow:'M5 12h14 M13 6l6 6-6 6',right:'M9 5l7 7-7 7',left:'M15 5l-7 7 7 7',layers:'M12 3L2 8l10 5 10-5-10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',perspective:'M3 8l14-5 4 13-14 5L3 8z M3 8l18 8 M17 3L7 21',hand:'M8 12V6a2 2 0 014 0v5 M12 10V4a2 2 0 014 0v7 M16 10V6a2 2 0 014 0v9c0 5-3 7-7 7-3 0-5-2-7-5l-3-5a2 2 0 013-2l2 2',list:'M8 6h13 M8 12h13 M8 18h13 M3 6h.01 M3 12h.01 M3 18h.01',compass:'M22 12a10 10 0 11-20 0 10 10 0 0120 0 M16 8l-3 5-5 3 3-5 5-3z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1116 0 M15 10a3 3 0 11-6 0 3 3 0 016 0',gate:'M3 21V7l9-4 9 4v14 M3 8h18 M7 8v13 M17 8v13 M7 15h10 M11 15v6 M14 15v6',tree:'M12 3l6 7h-3l5 6h-7v5h-2v-5H4l5-6H6l6-7z',water:'M2 17c2-3 4 3 6 0s4 3 6 0 4 3 8 0 M2 21c2-3 4 3 6 0s4 3 6 0 4 3 8 0 M12 2S7 8 7 10a5 5 0 0010 0c0-2-5-8-5-8z',truck:'M2 5h12v12H2V5z M14 9h4l4 4v4h-8 M4 17a2 2 0 104 0 M16 17a2 2 0 104 0 M18 9v4h4',leaf:'M20 3C8 1 2 7 5 15c8 5 16-2 15-12z M3 21l12-13',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',keyboard:'M3 5h18v14H3z M6 9h.01 M10 9h.01 M14 9h.01 M18 9h.01 M6 12h.01 M10 12h.01 M14 12h.01 M18 12h.01 M8 16h8'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.pin}"/></svg>`;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}icons();
const places=[
 {id:'portaria',title:'Acesso principal',short:'Acesso principal',subtitle:'A primeira conexão',icon:'gate',x:18.3,y:71.7,zoom:2.1,kicker:'CHEGADA / ACESSO',image:'assets/portaria.webp',description:'Uma nova perspectiva da chegada ao Metropolitan. A cobertura de acesso, a recepção e o paisagismo compõem o primeiro contato com o empreendimento.',tags:['Pórtico de acesso','Recepção','Paisagismo'],note:'Perspectiva ilustrativa baseada no projeto de portaria fornecido.'},
 {id:'convivencia',title:'Áreas de convivência',short:'Convivência',subtitle:'Uma pausa no seu dia',icon:'leaf',x:28.6,y:39.7,zoom:1.8,kicker:'CONEXÕES / CONVIVÊNCIA',image:'assets/convivencia.webp',description:'Percursos a pé, pergolados e espaços de estar trazem uma escala mais humana ao ambiente empresarial.',tags:['Pergolados','Espaços de estar','Caminhos verdes'],note:'Perspectiva ilustrativa. A posição do ponto de visita é indicativa.'},
 {id:'logistica',title:'Perspectiva empresarial',short:'Circulação',subtitle:'Espaço para movimentar',icon:'truck',x:73.1,y:76.4,zoom:1.6,kicker:'MOVIMENTO / NEGÓCIOS',image:'assets/logistica.webp',description:'Conheça uma possibilidade de ocupação empresarial, com galpões, fachadas corporativas e circulação de veículos representados em uma nova renderização.',tags:['Circulação','Galpões conceituais','Frentes empresariais'],note:'Ocupação conceitual, sem indicação de empresas instaladas ou uso aprovado para um lote específico.'},
 {id:'corredor',title:'Corredor verde',short:'Corredor verde',subtitle:'Natureza entre as quadras',icon:'tree',x:47.5,y:35.9,zoom:1.7,kicker:'PAISAGEM / CORREDOR VERDE',description:'O eixo verde central acompanha o curso d’água e organiza a leitura da implantação. Explore a relação entre a paisagem, as vias e as quadras.',tags:['Vegetação','Curso d’água','Paisagem'],note:'Visualização da implantação fornecida.'},
 {id:'lagoa',title:'Água e paisagem',short:'Água e paisagem',subtitle:'Um encontro de caminhos',icon:'water',x:36.8,y:57.1,zoom:2.2,kicker:'PAISAGEM / ÁGUA',description:'O espelho d’água aparece junto à conexão viária central, próximo ao bosque e ao acesso. Aproxime a implantação para observar esse encontro.',tags:['Espelho d’água','Bosque','Conexão central'],note:'Visualização da implantação fornecida.'}
];
const blocks=[
 {id:'q1',n:1,x:20.6,y:28.6,zoom:1.35,position:'Faixa oeste',description:'Quadra longitudinal no lado oeste da implantação, acompanhando a via de acesso interna.',poly:'338,76 412,100 255,547 199,645 167,609'},
 {id:'q2',n:2,x:35.8,y:23.2,zoom:1.6,position:'Setor noroeste',description:'Quadra na porção superior esquerda, envolvida pelo circuito viário e próxima ao corredor verde central.',poly:'445,98 576,134 585,148 490,467 459,457 326,420'},
 {id:'q3',n:3,x:24.8,y:59.4,zoom:1.6,position:'Próxima ao acesso',description:'Quadra no setor inferior esquerdo da implantação, próxima ao acesso principal e ao bosque.',poly:'321,443 483,489 396,767 213,790 181,762 177,662 245,664 266,651'},
 {id:'q4',n:4,x:54.6,y:48.3,zoom:2.1,position:'Conexão central',description:'Quadra junto à conexão entre os dois lados do empreendimento, no início da sequência de quadras do setor leste.',poly:'731,437 836,538 815,554 793,585 767,675 737,699 663,654'},
 {id:'q5',n:5,x:62.2,y:55.8,zoom:1.7,position:'Setor leste',description:'Quadra alongada do setor leste, entre a conexão central e as quadras 6 e 7.',poly:'850,547 942,627 905,692 862,827 813,823 776,801 754,735 797,642 826,573'},
 {id:'q6',n:6,x:70.4,y:63.5,zoom:1.8,position:'Setor sudeste',description:'Quadra situada entre as quadras 5 e 7, com frentes voltadas ao circuito viário do setor sudeste.',poly:'960,642 1055,728 1022,779 980,881 881,850 901,782'},
 {id:'q7',n:7,x:81.2,y:70,zoom:1.8,position:'Extremidade sudeste',description:'Quadra na extremidade sudeste do circuito, vizinha à quadra 8 e à curva da via perimetral.',poly:'1071,744 1191,837 1150,935 1008,899 1035,800'},
 {id:'q8',n:8,x:90,y:81.5,zoom:1.7,position:'Extensão sudeste',description:'Área de geometria irregular na continuação do setor sudeste, identificada como quadra 8 na implantação.',poly:'1224,819 1372,949 1372,991 1350,1016 1175,973'},
 {id:'q9',n:9,x:58.8,y:24.8,zoom:1.45,position:'Braço nordeste',description:'Quadra em L no alto da implantação, acompanhando a via que termina em retorno circular.',poly:'797,190 1033,242 1032,283 1084,286 1072,336 846,289 878,500 783,428 733,367'}
];
const scenePlaces=[{id:'aerea',title:'Visão aérea do Metropolitan',image:'assets/visao-aerea.jpg'},...places.filter(p=>p.image)],tourOrder=['portaria','convivencia','corredor','lagoa','logistica'];
let active=null,tab='places',pointsVisible=true,tilted=false,presenting=false,toastTimer;
const stage=$('#map-stage'),map=$('#map'),image=$('#masterplan');
const camera={x:0,y:0,s:1,min:.1,max:4},size={w:1372,h:1148};let animation=0,resizePending=0;
function draw(){stage.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.s})${tilted?' perspective(1700px) rotateX(18deg)':''}`;stage.style.setProperty('--marker-scale',1/camera.s);$('#zoom-label').textContent=Math.round(camera.s/camera.min*100)+'%';$('#zoom-in').disabled=camera.s>=camera.max-.01;$('#zoom-out').disabled=camera.s<=camera.min+.001;}
function bounds(x,y,s){const w=map.clientWidth,h=map.clientHeight,pad=Math.min(w,h)*.38;return{x:Math.max(-size.w*s+pad,Math.min(w-pad,x)),y:Math.max(-size.h*s+pad,Math.min(h-pad,y))};}
function move(x,y,s,animate=false){cancelAnimationFrame(animation);s=Math.min(camera.max,Math.max(camera.min,s));({x,y}=bounds(x,y,s));if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches){Object.assign(camera,{x,y,s});draw();return;}const from={...camera},start=performance.now();const tick=t=>{const p=Math.min((t-start)/650,1),e=1-Math.pow(1-p,3);camera.x=from.x+(x-from.x)*e;camera.y=from.y+(y-from.y)*e;camera.s=from.s+(s-from.s)*e;draw();if(p<1)animation=requestAnimationFrame(tick);};animation=requestAnimationFrame(tick);}
function fit(animate=true){const pad=matchMedia('(max-width:600px)').matches?25:36,w=map.clientWidth,h=map.clientHeight;camera.min=Math.min((w-pad*2)/size.w,(h-pad*2)/size.h);camera.max=Math.max(3.2,camera.min*6);move((w-size.w*camera.min)/2,(h-size.h*camera.min)/2,camera.min,animate);}
function zoom(factor,px=map.clientWidth/2,py=map.clientHeight/2){const ns=Math.min(camera.max,Math.max(camera.min,camera.s*factor)),r=ns/camera.s;move(px-(px-camera.x)*r,py-(py-camera.y)*r,ns);}
function focus(p){const isMobile=map.clientWidth<600,ns=camera.min*p.zoom;const cx=map.clientWidth*(isMobile?.5:.39),cy=map.clientHeight*(isMobile?.32:.49);move(cx-p.x/100*size.w*ns,cy-p.y/100*size.h*ns,ns,true);}
function listPlace(p){return`<button class="place-item" data-place="${p.id}" aria-pressed="false"><span class="place-icon">${icon(p.icon)}</span><span class="place-label"><strong>${p.title}</strong><small>${p.subtitle}</small></span>${icon('right')}</button>`;}
$('#places-list').innerHTML=places.map(listPlace).join('');
$('#blocks-list').innerHTML=blocks.map(b=>`<button class="place-item" data-block="${b.id}" aria-pressed="false"><span class="place-icon block-number">${String(b.n).padStart(2,'0')}</span><span class="place-label"><strong>Quadra ${b.n}</strong><small>${b.position}</small></span>${icon('right')}</button>`).join('');
$('#markers').innerHTML=places.map(p=>`<button class="map-marker" data-place="${p.id}" style="left:${p.x}%;top:${p.y}%" aria-label="Explorar ${p.title}" aria-pressed="false">${icon(p.icon)}<span>${p.short}</span></button>`).join('');
$('#block-markers').innerHTML=blocks.map(b=>`<button class="block-marker" data-block="${b.id}" style="left:${b.x}%;top:${b.y}%" aria-label="Explorar quadra ${b.n}" aria-pressed="false">Quadra <span>${b.n}</span></button>`).join('');
$('#block-layer').innerHTML=blocks.map(b=>`<polygon class="block-polygon" data-block="${b.id}" points="${b.poly}"><title>Quadra ${b.n}</title></polygon>`).join('');
function updateSelection(){ $$('[data-place]').forEach(e=>e.setAttribute('aria-pressed',e.dataset.place===active));$$('[data-block]').forEach(e=>{if(e.tagName.toLowerCase()==='button')e.setAttribute('aria-pressed',e.dataset.block===active);else e.classList.toggle('selected',e.dataset.block===active);});}
function changeTab(next){tab=next;$('#places-tab').setAttribute('aria-selected',next==='places');$('#blocks-tab').setAttribute('aria-selected',next==='blocks');$('#places-list').hidden=next!=='places';$('#blocks-list').hidden=next!=='blocks';setLayers();}
function setLayers(){$('#markers').hidden=!pointsVisible||tab!=='places';$('#block-markers').hidden=!pointsVisible||tab!=='blocks';$('#block-layer').style.visibility=pointsVisible?'visible':'hidden';stage.classList.toggle('show-blocks',tab==='blocks'&&pointsVisible);$('#layers-btn').setAttribute('aria-pressed',pointsVisible);$('#layers-btn').lastElementChild.textContent=pointsVisible?'Pontos visíveis':'Mostrar pontos';}
function showDetails(p,isBlock=false){$('#detail-panel').hidden=false;$('#detail-panel').classList.toggle('block-detail',isBlock);$('#detail-panel').classList.toggle('no-image',!p.image);$('#detail-image-btn').hidden=!p.image;if(p.image){$('#detail-image').src=p.image;$('#detail-image').alt=`Nova perspectiva ilustrativa: ${p.title}`;}$('#detail-kicker').textContent=isBlock?'IMPLANTAÇÃO / '+p.position:p.kicker;$('#detail-title').textContent=isBlock?'Quadra '+p.n:p.title;$('#detail-text').textContent=p.description;$('#detail-tags').innerHTML=(isBlock?['Quadra '+p.n,'Visualizar no mapa']:p.tags).map(t=>`<span>${t}</span>`).join('');$('#detail-note').textContent=isBlock?'Contornos de navegação aproximados. Consulte a planta técnica para limites e dimensões; disponibilidade e condições não são informadas neste mapa.':p.note;$('#detail-action').hidden=!p.image;map.classList.add('detail-open');$('#map-heading-title').textContent=isBlock?'Quadra '+p.n:p.title;}
function select(id,{byTour=false}={}){if(!byTour&&tour.running)stopTour();let p=places.find(v=>v.id===id),isBlock=false;if(!p){p=blocks.find(v=>v.id===id);isBlock=true;}if(!p)return;active=id;changeTab(isBlock?'blocks':'places');pointsVisible=true;setLayers();updateSelection();showDetails(p,isBlock);focus(p);closeSidebar();$('#mobile-explore').setAttribute('aria-expanded','false');history.replaceState(null,'','#'+id);}
function closeDetails(){active=null;$('#detail-panel').hidden=true;map.classList.remove('detail-open');updateSelection();$('#map-heading-title').textContent='O Metropolitan, por inteiro.';history.replaceState(null,'',location.pathname+location.search);}
function overview(){stopTour();closeDetails();tilted=false;$('#tilt-btn').setAttribute('aria-pressed',false);stage.classList.remove('tilted');fit();closeSidebar();}
$$('[data-place]').forEach(e=>e.addEventListener('click',()=>select(e.dataset.place)));
$$('[data-block]').forEach(e=>e.addEventListener('click',()=>select(e.dataset.block)));
$('#places-tab').onclick=()=>changeTab('places');$('#blocks-tab').onclick=()=>changeTab('blocks');
$$('[role=tab]').forEach((el,i)=>el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:1-i;changeTab(next?'blocks':'places');(next?$('#blocks-tab'):$('#places-tab')).focus();}}));
$('#close-detail').onclick=()=>{stopTour();closeDetails();};$('#fit-btn').onclick=overview;$('#brand-home').onclick=overview;$('#overview-btn').onclick=overview;
$('#zoom-in').onclick=()=>zoom(1.3);$('#zoom-out').onclick=()=>zoom(1/1.3);$('#layers-btn').onclick=()=>{pointsVisible=!pointsVisible;setLayers();};
$('#tilt-btn').onclick=()=>{tilted=!tilted;$('#tilt-btn').setAttribute('aria-pressed',tilted);stage.classList.toggle('tilted',tilted);draw();};
function syncSidebar(){const mobile=matchMedia('(max-width:900px)').matches;$('#sidebar').inert=mobile&&!$('#sidebar').classList.contains('is-open');}
function closeSidebar(){const hadFocus=$('#sidebar').contains(document.activeElement);$('#sidebar').classList.remove('is-open');$('#mobile-explore').setAttribute('aria-expanded','false');syncSidebar();if(hadFocus&&matchMedia('(max-width:900px)').matches)$('#mobile-explore').focus();}
$('#mobile-explore').setAttribute('aria-expanded','false');$('#mobile-explore').onclick=()=>{const open=$('#sidebar').classList.toggle('is-open');$('#mobile-explore').setAttribute('aria-expanded',open);syncSidebar();if(open)$('#sidebar-close').focus();};
matchMedia('(max-width:900px)').addEventListener('change',syncSidebar);syncSidebar();
$('#sidebar-close').onclick=()=>{closeSidebar();$('#mobile-explore').setAttribute('aria-expanded','false');$('#mobile-explore').focus();};
let pointers=new Map(),gesture=null;
map.addEventListener('pointerdown',e=>{if(e.target.closest('button,[data-block],.detail-panel,.tour-player'))return;cancelAnimationFrame(animation);map.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={type:'pan',x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};else{const [a,b]=[...pointers.values()],r=map.getBoundingClientRect();gesture={type:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),s:camera.s,cx:camera.x,cy:camera.y,mx:(a.x+b.x)/2-r.left,my:(a.y+b.y)/2-r.top};}map.classList.add('grabbed');});
map.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture.type==='pan'&&pointers.size===1)move(gesture.cx+e.clientX-gesture.x,gesture.cy+e.clientY-gesture.y,camera.s);else if(pointers.size===2){const[a,b]=[...pointers.values()],r=map.getBoundingClientRect(),ns=Math.max(camera.min,Math.min(camera.max,gesture.s*Math.hypot(a.x-b.x,a.y-b.y)/gesture.distance)),ratio=ns/gesture.s,mx=(a.x+b.x)/2-r.left,my=(a.y+b.y)/2-r.top;move(mx-(gesture.mx-gesture.cx)*ratio,my-(gesture.my-gesture.cy)*ratio,ns);}});
function release(e){pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];gesture={type:'pan',x:p.x,y:p.y,cx:camera.x,cy:camera.y};}else if(!pointers.size){gesture=null;map.classList.remove('grabbed');}}map.addEventListener('pointerup',release);map.addEventListener('pointercancel',release);
map.addEventListener('wheel',e=>{if(e.target.closest('.detail-panel'))return;e.preventDefault();const r=map.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
map.addEventListener('dblclick',e=>{if(e.target.closest('button,.detail-panel'))return;const r=map.getBoundingClientRect();zoom(1.5,e.clientX-r.left,e.clientY-r.top);});
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function present(enable){presenting=enable;document.body.classList.toggle('presenting',enable);$('#presentation-bar').hidden=!enable;if(enable){stopTour();closeDetails();}requestAnimationFrame(()=>fit(false));}
$('#present-btn').onclick=()=>present(true);$('#exit-presentation').onclick=()=>present(false);
$('#fullscreen-btn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else present(true);}catch{present(true);}};
document.addEventListener('fullscreenchange',()=>{icons();requestAnimationFrame(()=>fit(false));});
const tour={running:false,paused:false,index:0,timer:0,start:0,duration:8500,elapsed:0};
function tourVisit(){select(tourOrder[tour.index],{byTour:true});$('#tour-count').textContent=String(tour.index+1).padStart(2,'0')+' / '+String(tourOrder.length).padStart(2,'0');$('#tour-name').textContent=places.find(p=>p.id===tourOrder[tour.index]).short;tour.start=performance.now();tour.elapsed=0;$('#tour-progress').style.width='0%';}
function tourTick(t){if(!tour.running)return;if(!tour.paused){const elapsed=t-tour.start;$('#tour-progress').style.width=Math.min(elapsed/tour.duration*100,100)+'%';if(elapsed>=tour.duration){if(tour.index===tourOrder.length-1){stopTour();toast('Percurso concluído. Continue explorando no seu ritmo.');return;}tour.index++;tourVisit();}}tour.timer=requestAnimationFrame(tourTick);}
function startTour(){if(tour.running){stopTour();return;}tour.running=true;tour.paused=false;tour.index=0;$('#tour-player').hidden=false;map.classList.add('tour-active');$('#tour-btn').lastElementChild.textContent='Encerrar percurso';$('#tour-pause').innerHTML=icon('pause');$('#tour-pause').setAttribute('aria-label','Pausar percurso');tourVisit();tour.timer=requestAnimationFrame(tourTick);}
function stopTour(){tour.running=false;cancelAnimationFrame(tour.timer);$('#tour-player').hidden=true;map.classList.remove('tour-active');$('#tour-btn').lastElementChild.textContent='Percurso guiado';}
$('#tour-btn').onclick=startTour;$('#tour-stop').onclick=stopTour;$('#tour-next').onclick=()=>{tour.index=(tour.index+1)%tourOrder.length;tourVisit();};$('#tour-prev').onclick=()=>{tour.index=(tour.index-1+tourOrder.length)%tourOrder.length;tourVisit();};$('#tour-pause').onclick=()=>{tour.paused=!tour.paused;if(tour.paused)tour.elapsed=performance.now()-tour.start;else tour.start=performance.now()-tour.elapsed;$('#tour-pause').innerHTML=icon(tour.paused?'play':'pause');$('#tour-pause').setAttribute('aria-label',tour.paused?'Continuar percurso':'Pausar percurso');};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&tour.running&&!tour.paused)$('#tour-pause').click();});
let galleryIndex=0,galleryScale=1,gx=0,gy=0,galleryPointer=null;const gallery=$('#gallery-dialog'),gimage=$('#gallery-image');
function galleryDraw(){gimage.style.transform=`translate(${gx}px,${gy}px) scale(${galleryScale})`;$('#gallery-reset').textContent=Math.round(galleryScale*100)+'%';$('#gallery-minus').disabled=galleryScale<=1;$('#gallery-plus').disabled=galleryScale>=3;}
function galleryReset(){galleryScale=1;gx=gy=0;galleryDraw();}
function galleryChange(index){galleryIndex=(index+scenePlaces.length)%scenePlaces.length;const p=scenePlaces[galleryIndex];$('#gallery-title').textContent=p.title;gimage.src=p.image;gimage.alt=`Perspectiva renderizada do Metropolitan: ${p.title}`;$('#gallery-description').textContent=p.id==='aerea'?'Uma visão do conjunto: acessos, espaços empresariais, água e paisagem.':p.id==='portaria'?'A arquitetura de chegada e o paisagismo do acesso.':p.id==='convivencia'?'Percursos, pergolados e espaços para uma pausa ao ar livre.':'Uma possibilidade de ocupação e circulação no ambiente empresarial.';$('#gallery-map').innerHTML=icon('map')+(p.id==='aerea'?'Ver implantação':'Ver no mapa');$('#gallery-dots').innerHTML=scenePlaces.map((p,i)=>`<button aria-label="Ver ${p.title}" aria-pressed="${i===galleryIndex}" data-gallery-index="${i}"></button>`).join('');$$('[data-gallery-index]').forEach(e=>e.onclick=()=>galleryChange(+e.dataset.galleryIndex));galleryReset();}
function openGallery(id='aerea'){stopTour();galleryChange(Math.max(0,scenePlaces.findIndex(p=>p.id===id)));gallery.showModal();}
$('#gallery-btn').onclick=()=>openGallery();$$('[data-scene]').forEach(e=>e.onclick=()=>openGallery(e.dataset.scene));$('#detail-image-btn').onclick=()=>openGallery(active);$('#detail-action').onclick=()=>openGallery(active);$('#gallery-close').onclick=()=>gallery.close();$('#gallery-prev').onclick=()=>galleryChange(galleryIndex-1);$('#gallery-next').onclick=()=>galleryChange(galleryIndex+1);$('#gallery-map').onclick=()=>{gallery.close();if(scenePlaces[galleryIndex].id==='aerea'){overview();changeTab('places');}else select(scenePlaces[galleryIndex].id);};
function galleryZoom(factor){galleryScale=Math.max(1,Math.min(3,galleryScale*factor));if(galleryScale===1)gx=gy=0;galleryDraw();}
$('#gallery-plus').onclick=()=>galleryZoom(1.35);$('#gallery-minus').onclick=()=>galleryZoom(1/1.35);$('#gallery-reset').onclick=galleryReset;
$('#gallery-viewport').addEventListener('wheel',e=>{e.preventDefault();galleryZoom(Math.exp(-e.deltaY*.002));},{passive:false});
$('#gallery-viewport').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;galleryPointer={id:e.pointerId,x:e.clientX,y:e.clientY,gx,gy};e.currentTarget.setPointerCapture(e.pointerId);});
$('#gallery-viewport').addEventListener('pointermove',e=>{if(!galleryPointer||e.pointerId!==galleryPointer.id||galleryScale<=1)return;const maxX=gimage.clientWidth*(galleryScale-1)/2,maxY=gimage.clientHeight*(galleryScale-1)/2;gx=Math.max(-maxX,Math.min(maxX,galleryPointer.gx+e.clientX-galleryPointer.x));gy=Math.max(-maxY,Math.min(maxY,galleryPointer.gy+e.clientY-galleryPointer.y));galleryDraw();});
$('#gallery-viewport').addEventListener('pointerup',e=>{if(galleryPointer&&galleryScale===1&&Math.abs(e.clientX-galleryPointer.x)>60)galleryChange(galleryIndex+(e.clientX<galleryPointer.x?1:-1));galleryPointer=null;});$('#gallery-viewport').addEventListener('pointercancel',()=>galleryPointer=null);
$('#help-btn').onclick=()=>$('#help-dialog').showModal();$('#help-close').onclick=()=>$('#help-dialog').close();$('#help-start').onclick=()=>{$('#help-dialog').close();map.focus();};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;if(gallery.open){if(e.key==='ArrowRight'){e.preventDefault();galleryChange(galleryIndex+1);}if(e.key==='ArrowLeft'){e.preventDefault();galleryChange(galleryIndex-1);}return;}if($('#help-dialog').open)return;if(e.key==='Escape'){if(presenting)present(false);else{stopTour();closeDetails();closeSidebar();}return;}if(e.target.closest('button')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;switch(e.key){case '+':case '=':e.preventDefault();zoom(1.3);break;case '-':e.preventDefault();zoom(1/1.3);break;case '0':overview();break;case 'ArrowLeft':e.preventDefault();move(camera.x+60,camera.y,camera.s);break;case 'ArrowRight':e.preventDefault();move(camera.x-60,camera.y,camera.s);break;case 'ArrowUp':e.preventDefault();move(camera.x,camera.y+60,camera.s);break;case 'ArrowDown':e.preventDefault();move(camera.x,camera.y-60,camera.s);break;}});
new ResizeObserver(()=>{cancelAnimationFrame(resizePending);resizePending=requestAnimationFrame(()=>{fit(false);if(active){const p=places.find(p=>p.id===active)||blocks.find(p=>p.id===active);if(p)focus(p);}});}).observe(map);
function ready(){$('#map-loading').hidden=true;fit(false);const id=location.hash.slice(1);if(places.some(p=>p.id===id)||blocks.some(p=>p.id===id))select(id);}
image.addEventListener('load',ready,{once:true});image.addEventListener('error',()=>{$('#map-loading').innerHTML='Não foi possível carregar o mapa. <button class="primary-button" id="reload-map">Tentar novamente</button>';$('#reload-map').onclick=()=>location.reload();},{once:true});if(image.complete&&image.naturalWidth)ready();
setLayers();
