-- Migração idempotente para observabilidade do cliente.
-- Validada dentro de transação e revertida durante o ciclo.
create table if not exists public.client_error_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete set null,
  session_id text not null,
  app_version text not null,
  severity text not null default 'error',
  message text not null,
  stack text null,
  route text null,
  user_agent text null,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.client_error_events enable row level security;

create index if not exists client_error_events_created_at_idx
  on public.client_error_events(created_at desc);

create index if not exists client_error_events_app_version_idx
  on public.client_error_events(app_version, created_at desc);

do $$ begin
  create policy "client telemetry insert" on public.client_error_events
  for insert with check (
    (auth.uid() is null and user_id is null)
    or (auth.uid() is not null and user_id = auth.uid())
  );
exception when duplicate_object then null; end $$;
