'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const paths={map:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2V5z M9 3v16 M15 5v16',image:'M4 3h16a1 1 0 011 1v16a1 1 0 01-1 1H4a1 1 0 01-1-1V4a1 1 0 011-1z M3 16l5-5 6 6 3-3 4 4 M15 8h.01',play:'M8 4l12 8-12 8z',pause:'M8 5v14 M16 5v14',help:'M9 9a3 3 0 016 0c0 2-3 2-3 4 M12 17h.01 M22 12a10 10 0 11-20 0 10 10 0 0120 0',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',focus:'M8 3H3v5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M9 9h6v6H9z',expand:'M8 3H3v5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M3 3l6 6 M21 3l-6 6 M21 21l-6-6 M3 21l6-6',collapse:'M9 3v6H3 M15 3v6h6 M15 21v-6h6 M9 21v-6H3',close:'M6 6l12 12 M18 6L6 18',arrow:'M5 12h14 M13 6l6 6-6 6',right:'M9 5l7 7-7 7',left:'M15 5l-7 7 7 7',layers:'M12 3L2 8l10 5 10-5-10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',perspective:'M3 8l14-5 4 13-14 5L3 8z M3 8l18 8 M17 3L7 21',hand:'M8 12V6a2 2 0 014 0v5 M12 10V4a2 2 0 014 0v7 M16 10V6a2 2 0 014 0v9c0 5-3 7-7 7-3 0-5-2-7-5l-3-5a2 2 0 013-2l2 2',list:'M8 6h13 M8 12h13 M8 18h13 M3 6h.01 M3 12h.01 M3 18h.01',compass:'M22 12a10 10 0 11-20 0 10 10 0 0120 0 M16 8l-3 5-5 3 3-5 5-3z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1116 0 M15 10a3 3 0 11-6 0 3 3 0 016 0',gate:'M3 21V7l9-4 9 4v14 M3 8h18 M7 8v13 M17 8v13 M7 15h10 M11 15v6 M14 15v6',tree:'M12 3l6 7h-3l5 6h-7v5h-2v-5H4l5-6H6l6-7z',water:'M2 17c2-3 4 3 6 0s4 3 6 0 4 3 8 0 M2 21c2-3 4 3 6 0s4 3 6 0 4 3 8 0 M12 2S7 8 7 10a5 5 0 0010 0c0-2-5-8-5-8z',truck:'M2 5h12v12H2V5z M14 9h4l4 4v4h-8 M4 17a2 2 0 104 0 M16 17a2 2 0 104 0 M18 9v4h4',leaf:'M20 3C8 1 2 7 5 15c8 5 16-2 15-12z M3 21l12-13',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',keyboard:'M3 5h18v14H3z M6 9h.01 M10 9h.01 M14 9h.01 M18 9h.01 M6 12h.01 M10 12h.01 M14 12h.01 M18 12h.01 M8 16h8'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.pin}"/></svg>`;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}icons();
const sourceScenes=[
  {id:'geral',name:'Visão geral',tag:'O empreendimento',x:.5,y:.5,z:1,info:'Explore o masterplan completo, com a Praça, a Portaria e o Bosque e Pista de Caminhada identificados.'},
  {id:'portaria',name:'Portaria',tag:'Acesso ao Solaris',x:.5628,y:.5108,z:4.1,featured:true,info:'Implantação ilustrativa da portaria no ponto indicado, junto ao clube e às quadras. A representação não substitui o projeto arquitetônico.'},
  {id:'praca',name:'Praça',tag:'Convivência & paisagismo',x:.6490,y:.4753,z:3.8,featured:true,info:'Praça paisagística na área triangular próxima ao clube e às quadras. Explore os caminhos e os espaços de convivência representados na imagem.'},
  {id:'bosque',name:'Bosque e Pista de Caminhada',tag:'Natureza & caminhada',x:.3146,y:.2095,z:3.15,featured:true,info:'Faixa verde entre as quadras residenciais, com bosque e pista de caminhada. A imagem preserva o traçado dos caminhos e o paisagismo de referência.'},
  {id:'lago',name:'Lago e Deck',tag:'Natureza & convivência',x:.155,y:.327,z:2.65,info:'Explore a margem do lago, os decks e a vegetação representados na imagem.'},
  {id:'clube',name:'Clube e Piscinas',tag:'Lazer & encontro',x:.588,y:.405,z:3.4,info:'Aproxime o núcleo do clube, as piscinas e sua relação com o entorno.'},
  {id:'quadras',name:'Quadras',tag:'Esporte & movimento',x:.584,y:.477,z:3.7,info:'Veja o setor esportivo e a conexão com as áreas de lazer do masterplan.'},
  {id:'hipica',name:'Centro Hípico',tag:'Experiência equestre',x:.428,y:.682,z:3,info:'Percorra visualmente a arena, as instalações de apoio e a faixa verde ao redor.'},
  {id:'acesso',name:'Acesso principal',tag:'Conexão viária externa',x:.927,y:.392,z:2.55,info:'Conexão viária externa representada na imagem. A Portaria do Solaris está identificada separadamente, junto ao setor de lazer.'},
  {id:'parque',name:'Parque das Árvores',tag:'Bairro planejado',x:.751,y:.283,z:2,info:'Explore as quadras do Bairro Parque das Árvores integradas ao conjunto.'}
];
const places=sourceScenes.filter(p=>p.id!=='geral').map(p=>({id:p.id,title:p.name,short:({bosque:'Bosque e caminhada',quadras:'Quadras esportivas',parque:'Parque das Árvores'})[p.id]||p.name,subtitle:p.tag,icon:({portaria:'gate',praca:'leaf',bosque:'tree',lago:'water',clube:'water',quadras:'grid',hipica:'leaf',acesso:'pin',parque:'tree'})[p.id],x:p.x*100,y:p.y*100,zoom:p.z,kicker:p.tag.toUpperCase(),image:['portaria','clube','lago'].includes(p.id)?'assets/'+p.id+'.webp':null,description:({portaria:'Uma perspectiva da chegada ao Solaris, com recepção, cobertura de acesso e paisagismo integrado.',clube:'Clube e piscinas em uma nova perspectiva, com espaços de descanso e convivência em meio ao verde.',lago:'O lago, os decks e os espaços de estar aproximam o cotidiano da paisagem natural.'})[p.id]||p.info,tags:[p.tag],note:'Perspectiva ilustrativa. Consulte o projeto para as características definitivas.'}));
const scenePlaces=[{id:'aerea',title:'Visão aérea do Solaris',image:'assets/masterplan.webp',description:'Uma visão do conjunto: áreas residenciais, clube, lago, bosque e centro hípico.'},...places.filter(p=>p.image)],tourOrder=['portaria','clube','quadras','praca','bosque','lago','hipica'];
let active=null,tab='places',pointsVisible=true,tilted=false,presenting=false,toastTimer;
const stage=$('#map-stage'),map=$('#map'),image=$('#masterplan');
const camera={x:0,y:0,s:1,min:.1,max:4},size={w:1448,h:1086};let animation=0,resizePending=0;
function draw(){stage.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.s})${tilted?' perspective(1700px) rotateX(18deg)':''}`;stage.style.setProperty('--marker-scale',1/camera.s);$('#zoom-label').textContent=Math.round(camera.s/camera.min*100)+'%';$('#zoom-in').disabled=camera.s>=camera.max-.01;$('#zoom-out').disabled=camera.s<=camera.min+.001;}
function bounds(x,y,s){const w=map.clientWidth,h=map.clientHeight,pad=Math.min(w,h)*.38;return{x:Math.max(-size.w*s+pad,Math.min(w-pad,x)),y:Math.max(-size.h*s+pad,Math.min(h-pad,y))};}
function move(x,y,s,animate=false){cancelAnimationFrame(animation);s=Math.min(camera.max,Math.max(camera.min,s));({x,y}=bounds(x,y,s));if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches){Object.assign(camera,{x,y,s});draw();return;}const from={...camera},start=performance.now();const tick=t=>{const p=Math.min((t-start)/650,1),e=1-Math.pow(1-p,3);camera.x=from.x+(x-from.x)*e;camera.y=from.y+(y-from.y)*e;camera.s=from.s+(s-from.s)*e;draw();if(p<1)animation=requestAnimationFrame(tick);};animation=requestAnimationFrame(tick);}
function fit(animate=true){const pad=matchMedia('(max-width:600px)').matches?25:36,w=map.clientWidth,h=map.clientHeight;camera.min=Math.min((w-pad*2)/size.w,(h-pad*2)/size.h);camera.max=Math.max(3.2,camera.min*12);move((w-size.w*camera.min)/2,(h-size.h*camera.min)/2,camera.min,animate);}
function zoom(factor,px=map.clientWidth/2,py=map.clientHeight/2){const ns=Math.min(camera.max,Math.max(camera.min,camera.s*factor)),r=ns/camera.s;move(px-(px-camera.x)*r,py-(py-camera.y)*r,ns);}
function focus(p){const isMobile=map.clientWidth<600,ns=camera.min*p.zoom;const cx=map.clientWidth*(isMobile?.5:.39),cy=map.clientHeight*(isMobile?.32:.49);move(cx-p.x/100*size.w*ns,cy-p.y/100*size.h*ns,ns,true);}
function listPlace(p){return`<button class="place-item" data-place="${p.id}" aria-pressed="false"><span class="place-icon">${icon(p.icon)}</span><span class="place-label"><strong>${p.title}</strong><small>${p.subtitle}</small></span>${icon('right')}</button>`;}
$('#places-list').innerHTML=places.map(listPlace).join('');
$('#blocks-list').innerHTML=blocks.map(b=>`<button class="place-item" data-block="${b.id}" aria-pressed="false"><span class="place-icon block-number">${b.n}</span><span class="place-label"><strong>Quadra ${b.n}</strong><small>${b.position}</small></span>${icon('right')}</button>`).join('');
$('#markers').innerHTML=places.map(p=>`<button class="map-marker" data-place="${p.id}" style="left:${p.x}%;top:${p.y}%" aria-label="Explorar ${p.title}" aria-pressed="false">${icon(p.icon)}<span>${p.short}</span></button>`).join('');
$('#block-markers').innerHTML=blocks.map(b=>`<button class="block-marker" data-block="${b.id}" style="left:${b.x}%;top:${b.y}%" aria-label="Explorar quadra ${b.n}" aria-pressed="false">Quadra <span>${b.n}</span></button>`).join('');
$('#block-layer').innerHTML=blocks.map(b=>`<polygon class="block-polygon" data-block="${b.id}" points="${b.poly}"><title>Quadra ${b.n}</title></polygon>`).join('');
const lotLabel=p=>`Lote ${String(p.n).padStart(2,'0')}`;
const lotButton=p=>`<button class="lot-choice${p.institutional?' institutional':''}" data-lot="${p.id}" aria-pressed="${active===p.id}" aria-label="Selecionar quadra ${p.block}, lote ${String(p.n).padStart(2,'0')}${p.institutional?', institucional':''}">${String(p.n).padStart(2,'0')}${p.institutional?'<small>INST.</small>':''}</button>`;
$('#lot-block').insertAdjacentHTML('beforeend',blocks.map(b=>`<option value="${b.n}">Quadra ${b.n}</option>`).join(''));
$('#lot-layer').innerHTML=lots.map(p=>`<polygon class="lot-polygon${p.institutional?' institutional':''}" data-lot="${p.id}" points="${p.poly}"><title>Quadra ${p.block} · ${lotLabel(p)}${p.institutional?' · Institucional':''}</title></polygon>`).join('');
function renderLotList(){
 const block=$('#lot-block').value,q=$('#lot-search').value.toUpperCase().replace(/QUADRA|LOTE/g,'').replace(/[^A-Z0-9]/g,'');
 const found=lots.filter(p=>(!block||p.block===block)&&(!q||[String(p.n),String(p.n).padStart(2,'0'),p.block+p.n,p.block+String(p.n).padStart(2,'0'),p.block].includes(q)));
 $('#lot-results').textContent=`${found.length} ${found.length===1?'lote encontrado':'lotes encontrados'}`;
 $('#lot-options').innerHTML=found.length?blocks.map(b=>{const group=found.filter(p=>p.block===b.n);return group.length?`<section class="lot-group"><h3>Quadra ${b.n}<small>${group.length} lotes</small></h3><div class="lot-grid">${group.map(lotButton).join('')}</div></section>`:'';}).join(''):'<p class="empty-lots">Nenhum lote com essa identificação. Experimente A 01 ou escolha outra quadra.</p>';
}
$('#lot-block').onchange=renderLotList;$('#lot-search').oninput=renderLotList;renderLotList();
document.addEventListener('click',e=>{const el=e.target.closest('button[data-lot]');if(el)select(el.dataset.lot);});
function updateSelection(){
 $$('[data-place]').forEach(e=>e.setAttribute('aria-pressed',e.dataset.place===active));
 $$('[data-block]').forEach(e=>{const selected=e.dataset.block===active;if(e.tagName.toLowerCase()==='button')e.setAttribute('aria-pressed',selected);else e.classList.toggle('selected',selected);});
 $$('[data-lot]').forEach(e=>{const selected=e.dataset.lot===active;if(e.tagName.toLowerCase()==='button')e.setAttribute('aria-pressed',selected);else e.classList.toggle('selected',selected);});
 const p=lots.find(p=>p.id===active),mark=$('#selected-lot-marker');mark.hidden=!p||tab!=='lots'||!pointsVisible;if(p){mark.textContent=`${p.block} · ${lotLabel(p)}`;mark.style.left=p.x+'%';mark.style.top=p.y+'%';}
}
function changeTab(next){
 tab=next;for(const name of ['places','blocks','lots']){$('#'+name+'-tab').setAttribute('aria-selected',name===next);$('#'+name+'-tab').tabIndex=name===next?0:-1;$('#'+name+'-list').hidden=name!==next;}
 if(active){const kind=lots.some(p=>p.id===active)?'lots':blocks.some(p=>p.id===active)?'blocks':'places';if(kind!==next)closeDetails();}
 setLayers();
}
function setLayers(){
 const technical=tab!=='places';$('#technical-wrap').hidden=!technical;$('#masterplan').hidden=technical;$('#portaria-implantacao').style.display=technical?'none':'';
 $('#markers').hidden=!pointsVisible||technical;$('#block-markers').hidden=!pointsVisible||tab!=='blocks';$('#block-layer').style.visibility=pointsVisible&&tab==='blocks'?'visible':'hidden';$('#lot-layer').style.visibility=pointsVisible&&tab==='lots'?'visible':'hidden';
 stage.classList.toggle('show-blocks',tab==='blocks'&&pointsVisible);stage.classList.toggle('show-lots',tab==='lots'&&pointsVisible);map.classList.toggle('technical-mode',technical);
 $('#map-mode-label').innerHTML=technical?'PLANTA DE LOTES · IDENTIFICAÇÃO ESQUEMÁTICA':'<i></i> IMPLANTAÇÃO INTERATIVA';
 $('#layers-btn').setAttribute('aria-pressed',pointsVisible);$('#layers-btn').lastElementChild.textContent=pointsVisible?'Pontos visíveis':'Mostrar pontos';updateSelection();
}
function showDetails(p,kind='places'){
 const isBlock=kind==='blocks',isLot=kind==='lots',title=isBlock?'Quadra '+p.n:isLot?lotLabel(p)+' · Quadra '+p.block:p.title;
 $('#detail-panel').hidden=false;$('#detail-panel').classList.toggle('block-detail',kind!=='places');$('#detail-panel').classList.toggle('no-image',!p.image);$('#detail-image-btn').hidden=!p.image;
 if(p.image){$('#detail-image').src=p.image;$('#detail-image').alt=`Perspectiva ilustrativa: ${p.title}`;}
 $('#detail-kicker').textContent=isBlock?'SOLARIS / '+p.position:isLot?'SOLARIS / IDENTIFICAÇÃO DO LOTE':p.kicker;
 $('#detail-title').textContent=title;
 $('#detail-text').textContent=isLot?(p.institutional?'Lote identificado como área institucional na planta de referência.':`Localizado na quadra ${p.block}. O contorno destacado mostra sua posição na planta de identificação.`):p.description;
 $('#detail-tags').innerHTML=(isBlock?[p.position]:isLot?['Quadra '+p.block,lotLabel(p),...(p.institutional?['Institucional']:[])]:p.tags).map(t=>`<span>${t}</span>`).join('');
 $('#detail-note').textContent=kind==='places'?p.note:'Identificação esquemática baseada na planta urbanística de 22/07/2025. Consulte o projeto para medidas e limites. Disponibilidade e valores sob consulta.';
 const dl=$('#detail-lots');dl.hidden=kind==='places';
 if(isBlock)dl.innerHTML='<p class="lot-detail-label">Selecione um lote</p><div class="lot-grid">'+lots.filter(l=>l.block===p.n).map(lotButton).join('')+'</div>';
 if(isLot){const group=lots.filter(l=>l.block===p.block),i=group.indexOf(p);dl.innerHTML=`<div class="lot-pagination"><button class="outline-button" data-lot="${group[(i-1+group.length)%group.length].id}" aria-label="Lote anterior">${icon('left')}Anterior</button><button class="outline-button" data-lot="${group[(i+1)%group.length].id}" aria-label="Próximo lote">Próximo${icon('right')}</button></div><button class="text-button" id="back-to-block">Ver toda a quadra ${p.block} ${icon('arrow')}</button>`;$('#back-to-block').onclick=()=>select('quadra-'+p.block.toLowerCase());}
 $('#detail-action').hidden=!p.image;map.classList.add('detail-open');$('#map-heading-title').textContent=title;
}
function select(id,{byTour=false}={}){
 if(!byTour&&tour.running)stopTour();const p=places.find(v=>v.id===id)||blocks.find(v=>v.id===id)||lots.find(v=>v.id===id);if(!p)return;
 const kind=lots.includes(p)?'lots':blocks.includes(p)?'blocks':'places';changeTab(kind);active=id;pointsVisible=true;setLayers();showDetails(p,kind);updateSelection();focus(p);closeSidebar();history.replaceState(null,'','#'+id);
}
function closeDetails(){active=null;$('#detail-panel').hidden=true;map.classList.remove('detail-open');updateSelection();$('#map-heading-title').textContent='O Solaris, por inteiro.';history.replaceState(null,'',location.pathname+location.search);}

function overview(){stopTour();closeDetails();changeTab('places');tilted=false;$('#tilt-btn').setAttribute('aria-pressed',false);stage.classList.remove('tilted');fit();closeSidebar();}
$$('[data-place]').forEach(e=>e.addEventListener('click',()=>select(e.dataset.place)));
$$('button[data-block]').forEach(e=>e.addEventListener('click',()=>select(e.dataset.block)));
for(const name of ['places','blocks','lots'])$('#'+name+'-tab').onclick=()=>{stopTour();changeTab(name);fit();};
$$('[role=tab]').forEach((el,i)=>el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=['places','blocks','lots'],n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;changeTab(tabs[n]);$('#'+tabs[n]+'-tab').focus();fit();}}));
$('#close-detail').onclick=()=>{stopTour();closeDetails();};$('#fit-btn').onclick=overview;$('#brand-home').onclick=overview;$('#overview-btn').onclick=overview;
$('#zoom-in').onclick=()=>zoom(1.3);$('#zoom-out').onclick=()=>zoom(1/1.3);$('#layers-btn').onclick=()=>{pointsVisible=!pointsVisible;setLayers();};
$('#tilt-btn').onclick=()=>{tilted=!tilted;$('#tilt-btn').setAttribute('aria-pressed',tilted);stage.classList.toggle('tilted',tilted);draw();};
function syncSidebar(){const mobile=matchMedia('(max-width:900px)').matches;$('#sidebar').inert=mobile&&!$('#sidebar').classList.contains('is-open');}
function closeSidebar(){const hadFocus=$('#sidebar').contains(document.activeElement);$('#sidebar').classList.remove('is-open');$('#mobile-explore').setAttribute('aria-expanded','false');syncSidebar();if(hadFocus&&matchMedia('(max-width:900px)').matches)$('#mobile-explore').focus();}
$('#mobile-explore').setAttribute('aria-expanded','false');$('#mobile-explore').onclick=()=>{const open=$('#sidebar').classList.toggle('is-open');$('#mobile-explore').setAttribute('aria-expanded',open);syncSidebar();if(open)$('#sidebar-close').focus();};
matchMedia('(max-width:900px)').addEventListener('change',syncSidebar);syncSidebar();
$('#sidebar-close').onclick=()=>{closeSidebar();$('#mobile-explore').setAttribute('aria-expanded','false');$('#mobile-explore').focus();};
let pointers=new Map(),gesture=null,parcelTap=null;
map.addEventListener('pointerdown',e=>{if(e.target.closest('button,.detail-panel,.tour-player'))return;const shape=e.target.closest('[data-lot],[data-block]');parcelTap=shape?{id:shape.dataset.lot||shape.dataset.block,x:e.clientX,y:e.clientY}:null;cancelAnimationFrame(animation);map.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={type:'pan',x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};else{parcelTap=null;const [a,b]=[...pointers.values()],r=map.getBoundingClientRect();gesture={type:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),s:camera.s,cx:camera.x,cy:camera.y,mx:(a.x+b.x)/2-r.left,my:(a.y+b.y)/2-r.top};}map.classList.add('grabbed');});
map.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;if(parcelTap&&Math.hypot(e.clientX-parcelTap.x,e.clientY-parcelTap.y)>7)parcelTap=null;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture.type==='pan'&&pointers.size===1)move(gesture.cx+e.clientX-gesture.x,gesture.cy+e.clientY-gesture.y,camera.s);else if(pointers.size===2){const[a,b]=[...pointers.values()],r=map.getBoundingClientRect(),ns=Math.max(camera.min,Math.min(camera.max,gesture.s*Math.hypot(a.x-b.x,a.y-b.y)/gesture.distance)),ratio=ns/gesture.s,mx=(a.x+b.x)/2-r.left,my=(a.y+b.y)/2-r.top;move(mx-(gesture.mx-gesture.cx)*ratio,my-(gesture.my-gesture.cy)*ratio,ns);}});
function release(e){const chosen=e.type==='pointerup'?parcelTap:null;parcelTap=null;pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];gesture={type:'pan',x:p.x,y:p.y,cx:camera.x,cy:camera.y};}else if(!pointers.size){gesture=null;map.classList.remove('grabbed');}if(chosen)select(chosen.id);}map.addEventListener('pointerup',release);map.addEventListener('pointercancel',release);
map.addEventListener('wheel',e=>{if(e.target.closest('.detail-panel'))return;e.preventDefault();const r=map.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);},{passive:false});
map.addEventListener('dblclick',e=>{if(e.target.closest('button,.detail-panel'))return;const r=map.getBoundingClientRect();zoom(1.5,e.clientX-r.left,e.clientY-r.top);});
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function present(enable){presenting=enable;document.body.classList.toggle('presenting',enable);$('#presentation-bar').hidden=!enable;if(enable){stopTour();closeDetails();}requestAnimationFrame(()=>fit(false));}
$('#present-btn').onclick=()=>present(true);$('#exit-presentation').onclick=()=>present(false);
$('#fullscreen-btn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else present(true);}catch{present(true);}};
document.addEventListener('fullscreenchange',()=>{icons();requestAnimationFrame(()=>fit(false));});
const tour={running:false,paused:false,index:0,timer:0,start:0,duration:8500,elapsed:0};
function tourVisit(){select(tourOrder[tour.index],{byTour:true});$('#tour-count').textContent=String(tour.index+1).padStart(2,'0')+' / '+String(tourOrder.length).padStart(2,'0');$('#tour-name').textContent=places.find(p=>p.id===tourOrder[tour.index]).short;tour.start=performance.now();tour.elapsed=0;$('#tour-progress').style.width='0%';}
function tourTick(t){if(!tour.running)return;if(!tour.paused){const elapsed=t-tour.start;$('#tour-progress').style.width=Math.min(elapsed/tour.duration*100,100)+'%';if(elapsed>=tour.duration){if(tour.index===tourOrder.length-1){stopTour();toast('Percurso concluído. Continue explorando no seu ritmo.');return;}tour.index++;tourVisit();}}tour.timer=requestAnimationFrame(tourTick);}
function startTour(){if(tour.running){stopTour();return;}tour.running=true;tour.paused=false;tour.index=0;$('#tour-player').hidden=false;map.classList.add('tour-active');$('#tour-btn').lastElementChild.textContent='Encerrar percurso';$('#tour-pause').innerHTML=icon('pause');$('#tour-pause').setAttribute('aria-label','Pausar percurso');tourVisit();tour.timer=requestAnimationFrame(tourTick);}
function stopTour(){tour.running=false;cancelAnimationFrame(tour.timer);$('#tour-player').hidden=true;map.classList.remove('tour-active');$('#tour-btn').lastElementChild.textContent='Percurso guiado';}
$('#tour-btn').onclick=startTour;$('#tour-stop').onclick=stopTour;$('#tour-next').onclick=()=>{tour.index=(tour.index+1)%tourOrder.length;tourVisit();};$('#tour-prev').onclick=()=>{tour.index=(tour.index-1+tourOrder.length)%tourOrder.length;tourVisit();};$('#tour-pause').onclick=()=>{tour.paused=!tour.paused;if(tour.paused)tour.elapsed=performance.now()-tour.start;else tour.start=performance.now()-tour.elapsed;$('#tour-pause').innerHTML=icon(tour.paused?'play':'pause');$('#tour-pause').setAttribute('aria-label',tour.paused?'Continuar percurso':'Pausar percurso');};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&tour.running&&!tour.paused)$('#tour-pause').click();});
let galleryIndex=0,galleryScale=1,gx=0,gy=0,galleryPointer=null;const gallery=$('#gallery-dialog'),gimage=$('#gallery-image');
function galleryDraw(){gimage.style.transform=`translate(${gx}px,${gy}px) scale(${galleryScale})`;$('#gallery-reset').textContent=Math.round(galleryScale*100)+'%';$('#gallery-minus').disabled=galleryScale<=1;$('#gallery-plus').disabled=galleryScale>=3;}
function galleryReset(){galleryScale=1;gx=gy=0;galleryDraw();}
function galleryChange(index){galleryIndex=(index+scenePlaces.length)%scenePlaces.length;const p=scenePlaces[galleryIndex];$('#gallery-title').textContent=p.title;gimage.src=p.image;gimage.alt=`Perspectiva renderizada do Solaris: ${p.title}`;$('#gallery-description').textContent=p.description;$('#gallery-map').innerHTML=icon('map')+(p.id==='aerea'?'Ver implantação':'Ver no mapa');$('#gallery-dots').innerHTML=scenePlaces.map((p,i)=>`<button aria-label="Ver ${p.title}" aria-pressed="${i===galleryIndex}" data-gallery-index="${i}"></button>`).join('');$$('[data-gallery-index]').forEach(e=>e.onclick=()=>galleryChange(+e.dataset.galleryIndex));galleryReset();}
function openGallery(id='aerea'){stopTour();galleryChange(Math.max(0,scenePlaces.findIndex(p=>p.id===id)));gallery.showModal();}
$('#gallery-btn').onclick=()=>openGallery();$$('[data-scene]').forEach(e=>e.onclick=()=>openGallery(e.dataset.scene));$('#detail-image-btn').onclick=()=>openGallery(active);$('#detail-action').onclick=()=>openGallery(active);$('#gallery-close').onclick=()=>gallery.close();$('#gallery-prev').onclick=()=>galleryChange(galleryIndex-1);$('#gallery-next').onclick=()=>galleryChange(galleryIndex+1);$('#gallery-map').onclick=()=>{gallery.close();if(scenePlaces[galleryIndex].id==='aerea'){overview();changeTab('places');}else select(scenePlaces[galleryIndex].id);};
function galleryZoom(factor){galleryScale=Math.max(1,Math.min(3,galleryScale*factor));if(galleryScale===1)gx=gy=0;galleryDraw();}
$('#gallery-plus').onclick=()=>galleryZoom(1.35);$('#gallery-minus').onclick=()=>galleryZoom(1/1.35);$('#gallery-reset').onclick=galleryReset;
$('#gallery-viewport').addEventListener('wheel',e=>{e.preventDefault();galleryZoom(Math.exp(-e.deltaY*.002));},{passive:false});
$('#gallery-viewport').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;galleryPointer={id:e.pointerId,x:e.clientX,y:e.clientY,gx,gy};e.currentTarget.setPointerCapture(e.pointerId);});
$('#gallery-viewport').addEventListener('pointermove',e=>{if(!galleryPointer||e.pointerId!==galleryPointer.id||galleryScale<=1)return;const maxX=gimage.clientWidth*(galleryScale-1)/2,maxY=gimage.clientHeight*(galleryScale-1)/2;gx=Math.max(-maxX,Math.min(maxX,galleryPointer.gx+e.clientX-galleryPointer.x));gy=Math.max(-maxY,Math.min(maxY,galleryPointer.gy+e.clientY-galleryPointer.y));galleryDraw();});
$('#gallery-viewport').addEventListener('pointerup',e=>{if(galleryPointer&&galleryScale===1&&Math.abs(e.clientX-galleryPointer.x)>60)galleryChange(galleryIndex+(e.clientX<galleryPointer.x?1:-1));galleryPointer=null;});$('#gallery-viewport').addEventListener('pointercancel',()=>galleryPointer=null);
$('#help-btn').onclick=()=>$('#help-dialog').showModal();$('#help-close').onclick=()=>$('#help-dialog').close();$('#help-start').onclick=()=>{$('#help-dialog').close();map.focus();};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select'))return;if(gallery.open){if(e.key==='ArrowRight'){e.preventDefault();galleryChange(galleryIndex+1);}if(e.key==='ArrowLeft'){e.preventDefault();galleryChange(galleryIndex-1);}return;}if($('#help-dialog').open)return;if(e.key==='Escape'){if(presenting)present(false);else{stopTour();closeDetails();closeSidebar();}return;}if(e.target.closest('button')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;switch(e.key){case '+':case '=':e.preventDefault();zoom(1.3);break;case '-':e.preventDefault();zoom(1/1.3);break;case '0':overview();break;case 'ArrowLeft':e.preventDefault();move(camera.x+60,camera.y,camera.s);break;case 'ArrowRight':e.preventDefault();move(camera.x-60,camera.y,camera.s);break;case 'ArrowUp':e.preventDefault();move(camera.x,camera.y+60,camera.s);break;case 'ArrowDown':e.preventDefault();move(camera.x,camera.y-60,camera.s);break;}});
new ResizeObserver(()=>{cancelAnimationFrame(resizePending);resizePending=requestAnimationFrame(()=>{fit(false);if(active){const p=places.find(p=>p.id===active)||blocks.find(p=>p.id===active)||lots.find(p=>p.id===active);if(p)focus(p);}});}).observe(map);
function ready(){$('#map-loading').hidden=true;fit(false);const id=location.hash.slice(1);if(places.some(p=>p.id===id)||blocks.some(p=>p.id===id)||lots.some(p=>p.id===id))select(id);}
image.addEventListener('load',ready,{once:true});image.addEventListener('error',()=>{$('#map-loading').innerHTML='Não foi possível carregar o mapa. <button class="primary-button" id="reload-map">Tentar novamente</button>';$('#reload-map').onclick=()=>location.reload();},{once:true});if(image.complete&&image.naturalWidth)ready();
setLayers();

$('#lot-map').addEventListener('error',()=>toast('A planta de lotes não carregou. Atualize a página para tentar novamente.'));
